### ISSUE TITLE
[Feature request]Item name and picture dumping

### ISSUE THREAD

**Issue by zlepper** [Chicken-Bones/NotEnoughItems#134]
The actual feature:
Like you can just dump item names, then an additional switch to enable dumping of all item textures like they appear in NEI together with their "name" like "minecraft:stone" for stone or "minecraft:dirt:2" for some special type of dirt, then with a reference to where the png or whatever NEI could make of the texture for that item/block.
I hope that made some kind of sence.

Now what I need this for:
I would like to make something so people can make MineTweaker recipes using only a GUI, no writing needed. 
I have also suggested this to the author of MineTweaker. https://github.com/stanhebben/MineTweaker3/issues/118
This is a really selfish and completely only useable by me feature, but I have no idea how to make mods for minecraft, and as NEI already does item name dumping this might be able to be added too.

**Comment by hnsl** [comment]
Awesome! This was exactly what I needed. To anyone else that finds this and doesn't understand how it works:

1. Start a new creative world.
2. Open inventory > Options > Tools > Data dumps.
3. Go to the "Item panel" dump
4. If you click "CSV" button you can change the dump type to "PNG"
5. Click on dump. Wait for it to complete.
6. Files now located at the /dumps/ directory in the Minecraft root.

**Comment by chriswa** [comment]
Thanks to you both for the feature and the explanation!!
