### ISSUE TITLE
Broken search behavior

### ISSUE THREAD

**Issue by Mengmoshu** [Chicken-Bones/NotEnoughItems#146]
NEI displays everything I expect it to on the right as long as the search box is empty, or using the @modname filtering. When I type in a search it seems to be only showing blocks and items by modname, not by the localized name the way it did in the past.

Not playing on a server, not using optifine or fastcraft. Launching with MultiMC5.

These are the mods I'm using that I think are likely to be involved.
NEI 1.0.4.83
NEI Addons 1.12.3.11
NEI Integration 1.0.3
NEI Mystcraft Plugin 01.05.01.00 (or maybe 02.00.00.00, metadata and filename don't agree.)
WAILA 1.5.8

It isn't crashing, so no relevant crashlogs.

I've got plenty of time to provide more information and try solutions.

**Comment by Chicken-Bones** [comment]
Update WAILA to 1.5.8a

**Comment by Mengmoshu** [comment]
Thanks. I'm not surprised it was WAILA, this is the 3rd version I've put in this instance to fix something it was doing to NEI. If I have any other odd experiences with NEI I'll check for a new WAILA version before trying anything else.
