### ISSUE TITLE
Crash when spawning items in when inventory is full

### ISSUE THREAD

**Issue by AnonymousPuppy** [Chicken-Bones/NotEnoughItems#153]
I'm using a custom modpack, forge .1240, and NotEnoughItems-1.7.10-1.0.3.78-universal.jar. Whenever I spawn any item in when my inventory is full, I crash. It happens consistently every time, and it only crashes when my inventory is completely full. 

Here is the crash report: http://pastebin.com/HiB9Gnqz

This isn't any significant issue, but it is a very annoying one. I can provide any additional information if necessary. Please look into this as soon as possible, thank you.

**Comment by Njet75** [comment]
Happens to me to.
Also tested NotEnoughItems-1.7.10-1.0.4.83 and still happens.

/Njet

**Comment by DerOli82** [comment]
Same here with 1.7.10-1.0.4.83.

Report: http://pastebin.com/eCsLFmbE

**Comment by mindcloud69** [comment]
Same here with 1.7.10-1.0.4.83.

http://pastebin.com/PTMHE2xs

**Comment by BBoldt** [comment]
Same issue, have another crashlog:

http://pastebin.com/ZJLh8EK5
