### ISSUE TITLE
NEI Crash in dev enviroment

### ISSUE THREAD

**Issue by Jayfeather311** [Chicken-Bones/NotEnoughItems#157]
When I start a new Environment i get a weird crash with NEI, CCC loads just fine, but when i add NEI it crashes with this error

http://pastebin.com/V36TG5Xd 
the problems starts at line 40 
Can anyone help me

**Comment by hockeyhurd** [comment]
I too have gotten this weird crash only just recently.  Of the few mods in my dev workspace I have removed all to make sure there were no conflicts yet same crash.  I too could add a crash log if need be but as stated the crash log is almost identical.

**Comment by modmuss50** [comment]
I cannot start it what so every in a dev env. I am getting this crash:

http://pastebin.com/tTEaQ7zj

**Comment by Chicken-Bones** [comment]
@Jayfeather311 You're missing CCL on your classpath in some form.
@modmuss50 Forge and NEI versions?

**Comment by modmuss50** [comment]
Forge: 1.8-11.14.1.1313
CodeChickenLib-1.8-1.1.2.131-dev
CodeChickenCore-1.8-1.0.5.34-dev
NotEnoughItems-1.8-1.0.5.88-dev

You can see the build.gradle here https://github.com/modmuss50/Network/blob/18/build.gradle#L95

I know CodeChickenLib is not being got from maven, but this should still work. It all builds and finds the CCL stuff just fine, it is just on runtime.

**Comment by Jayfeather311** [comment]
I have found out that it is the latest version of forge for 1.7.10. NEI somewhat works when it is not added to the build path, as in it doesnt show the items. When i do add it to the classpath, it gives be the error above. But when i add CodeChickenLib to the classpath i get the following error
http://pastebin.com/KMfDucFE
the error is farther down for CodeChickenLib

**Comment by alexbegt** [comment]
@modmuss50 With the latest builds of all 3, they shouldn't crash with 1.8 due to the mappings being changed and things renamed.
