### ISSUE TITLE
creative mode: empty page of project block subset tabs

### ISSUE THREAD

**Issue by moTechPlz** [Chicken-Bones/NotEnoughItems#162]
Minor issue:

When i have 20 project block subset tabs a empty 3th selection page is created. 
![2015-02-27_17 42 16](https://cloud.githubusercontent.com/assets/11203133/6416682/1f5c5c12-bea8-11e4-9b83-f02ed91a2826.png)
![2015-02-27_17 33 43](https://cloud.githubusercontent.com/assets/11203133/6416683/209c6022-bea8-11e4-9d61-3d31708372e3.png)

**Comment by cabralRodrigo** [comment]
Pretty sure that this is not a NEI issue.

**Comment by moTechPlz** [comment]
Right, that's part of vanilla, durp
