### ISSUE TITLE
Problem With Search

### ISSUE THREAD

**Issue by Jayjayx5x1** [Chicken-Bones/NotEnoughItems#164]
Hey Dav I seem to be unable to search items out of the item list, what happened is i accidentally double clicked the search bar and set it to search inventory i turned this off but now it won't search the item list so yeah help bud. p.s. you killed toomanyitems :P and to think in school i was like eh toomanyitems is still better XD

**Comment by Jayjayx5x1** [comment]
update: ok so it still works it just takes around 5 seconds for it to actually search any ideas how to fix?

**Comment by cabralRodrigo** [comment]
@Jayjayx5x1 Sometimes when you have a lot of stuff blacklisted, the search gets really slow. But I don't know if this issue has been fixed.

**Comment by Jayjayx5x1** [comment]
@cabralRodrigo i would assume that to fix it one would just restart mc?

**Comment by cabralRodrigo** [comment]
@Jayjayx5x1 When this happened to me, restarting mc doesn't fixed the issue
Maybe @Chicken-Bones can tell us if this issue still opens.

**Comment by Jayjayx5x1** [comment]
I'm sure they probably already know how to fix it
