### ISSUE TITLE
Fatal Crash - Updating Screen Event

### ISSUE THREAD

**Issue by Tim020** [Chicken-Bones/NotEnoughItems#179]
Entire game crashes when trying to add more items from NEI to your Inventory than the player has space for (I.e giving 3 stacks when only have room for 2)
Running the DW20 FTB 1.7.10 pack, version 1.2.1
Full crash log here: http://pastebin.com/3WY2d7JK

**Comment by Chicken-Bones** [comment]
Duplicate of #153
