### ISSUE TITLE
Crash after rejoining a server-minetweaker

### ISSUE THREAD

**Issue by TechGnome57** [Chicken-Bones/NotEnoughItems#180]
If you load your client then join a server, it works fine, but if you relog you will crash....  If you need a crash log say so, but you should catch the exceptions instead of letting minecraft crash.  The exception occured while using the regrowth FTB pack

**Comment by Chicken-Bones** [comment]
if course, logs or it didn't happen

**Comment by TechGnome57** [comment]
There you go: http://pastebin.com/svPgEyd9
The stack should give you all the information you need.

**Comment by Chicken-Bones** [comment]
at appeng.integration.modules.NEIHelpers.NEIInscriberRecipeHandler
Report to whoever makes the Applied Energistics NEI module

**Comment by Distjubo** [comment]
Your mod is involved and could catch this Exception. Look at the stacktrace. I decompiled your code, added a catch clause and it didn't crash. You could fix it.

**Comment by Chicken-Bones** [comment]
Just because I could, doesn't mean I should, nor that it's my responsibility.

**Comment by Distjubo** [comment]
Still, minecraft should not crash because of a few recipes.

**Comment by Chicken-Bones** [comment]
I agree, but I'm not the cause

**Comment by Chicken-Bones** [comment]
Feel free to patch this yourself and build a local version

**Comment by Distjubo** [comment]
I already did that :D
