### ISSUE TITLE
More Localization

### ISSUE THREAD

**Issue by Vexatos** [Chicken-Bones/NotEnoughItems#185]
Some things, like the "NEI Subsets" button, cannot be localized just yet. Might be worth looking through the code to find non-localizable strings.

**Comment by Adaptivity** [comment]
Ye olde thing: https://github.com/Chicken-Bones/NotEnoughItems/issues/47

**Comment by Adaptivity** [comment]
More stuff: https://github.com/Chicken-Bones/NotEnoughItems/blob/1.7/src/codechicken/nei/GuiPotionCreator.java#L300-L302

**Comment by Chicken-Bones** [comment]
Looks like I have a lot of time on my hands :L (sorry bout that)

**Comment by Adaptivity** [comment]
That means you gonna implement it?

**Comment by Chicken-Bones** [comment]
I hope so, but not right now, I've gotta go

**Comment by Chicken-Bones** [comment]
It's done d59b28f8fcce1b55af02e3429b522b6062f08643 (1.7.10-1.0.4.100)
The subsets will look for a localisation, and use the default if none exists, which means you can localise any subset option (even ones I haven't put in en_US)

**Comment by Adaptivity** [comment]
Cool. Can you add nei.options.keys.showenchant into .lang file? I don't know how this .lang key should be named. You should know better.

**Comment by Adaptivity** [comment]
And one more thing: http://i.imgur.com/H0HrkBj.jpg is it NEI string? I looked for it through code and through code of many mods and still can't find it

**Comment by Chicken-Bones** [comment]
Line number?

**Comment by Adaptivity** [comment]
As I say, I can't find it :smile: But it should be in NEI, I guess. Keybind is here: http://i.imgur.com/KugGoJG.jpg

**Comment by Chicken-Bones** [comment]
That would be a different mod :P, perhaps NEI Plugins

**Comment by Adaptivity** [comment]
Ok, just tested with only NEI installed (and CCC). And this tooltip still appears. You should look deeper into the code, I guess :smile:

**Comment by Chicken-Bones** [comment]
Nope? This is my dev http://puu.sh/hqiTY/adb73864de.jpg

**Comment by Adaptivity** [comment]
I'm using 1.0.4.95 and this string was here back in august 2014. It is development env? Try running normal env. It should be here. You also found out that your version checker is hardcoded too. You should move these messages into .lang too :smile:

**Comment by Chicken-Bones** [comment]
You sure, check your mods and version mods folders, and send a full FML log?

**Comment by Adaptivity** [comment]
Tracked this down. It happens with waila installed. Dunno why waila doing this... But at least "Recipes" string still somewhere in NEI because it's displays only with NEI installed.

**Comment by Chicken-Bones** [comment]
Yeah, Waila has some NEI integration, you should submit a bug report for
that mod's localisation

**Comment by Adaptivity** [comment]
I'll do that later. Will you check "Recipes" string later?

**Comment by Chicken-Bones** [comment]
Where is that?

**Comment by Adaptivity** [comment]
I don't know. It appears here: http://i.imgur.com/H0HrkBj.jpg and it appears with ONLY NEI installed. No other mods.

**Comment by Chicken-Bones** [comment]
Gotcha 46d7a84ecd8ab86dc530e1346ff73e9221277c77

**Comment by Adaptivity** [comment]
Thanks. And what about version checker messages? Which are pop up on your screenshot: http://puu.sh/hqiTY/adb73864de.jpg

**Comment by Chicken-Bones** [comment]
There you go https://github.com/Chicken-Bones/CodeChickenCore/commit/28d09c376c5bd81440f46d713c45e38d0f0cc8cd
