### ISSUE TITLE
NEI Item Loading thread has frequent timeouts

### ISSUE THREAD

**Issue by Parker8283** [Chicken-Bones/NotEnoughItems#186]
Every second or third time I start up the game, the NEI Item Loading thread times out, thus making it so I can't use NEI, and I have to restart the game to make it work. Running latest CCC and NEI for 1.7.10. Could the timeout time be extended, or maybe an option to restart the thread?

**Comment by Chicken-Bones** [comment]
timeout's shouldn't kill the thread, just remove the problematic items, do you have more evidence/data?

**Comment by Deathlymad** [comment]
I think I have something similar..
If I keep playing Minecraft too long this will start to appear frequently:

[02:55:57] [NEI Item Loading Operation Timer/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.UnsupportedOperationException
[02:55:57] [NEI Item Loading Operation Timer/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.Thread.stop(Unknown Source)
[02:55:57] [NEI Item Loading Operation Timer/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at codechicken.nei.ThreadOperationTimer.run(ThreadOperationTimer.java:59)

I am running the latest Version for 1.7.10. There are other mods in my instance but there are many and I don'T think they are causing the problem.
If it isn't code problem can you tell me how to avoid this error?

**Comment by Chicken-Bones** [comment]
It's Java 8 that's broken my code that handles bad item timeouts, I'll work on fixing this

**Comment by Parker8283** [comment]
I don't use Java 8

**Comment by Chicken-Bones** [comment]
@Deathlymad probably does, and he's the only one that gave me a log, I have no idea what's happening without logs

**Comment by Parker8283** [comment]
His log is exactly what I get. I'd give you a more complete log, but the computer this happens most often on has died :/

**Comment by Chicken-Bones** [comment]
If it's not Java 8, then I'll need to know the catalyst mod (which mod + NEI causes the issue)

**Comment by Deathlymad** [comment]
If you want to I can post my mod list but as i said no mod related stacktrace is printed and the modlist is long...
couldn't it be that some rendering code isn't supporpted in NEI Rendering...

**Comment by Deathlymad** [comment]
Oh wait nonnono I am soryy nvm how could i ever doubt THE CHICKEN-BONES

(I am totally honest I am truly admiering your code there is no sarcasm in the previous sentence)

**Comment by Chicken-Bones** [comment]
It's quite possible I'm doing something wrong. It's almost certain I'm not handling some mod with enough care, but I don't know which one it is, or what care to give it, if you send me a zip with mods and configs I should be able to fix it
