### ISSUE TITLE
java.lang.IllegalArgumentException: Cannot create a fluidstack from a null fluid

### ISSUE THREAD

**Issue by loordgek** [Chicken-Bones/NotEnoughItems#188]
when i try to look up "tank" in nei http://paste.ee/p/tZO5D

**Comment by efalder413** [comment]
This might be a Forge issue, as the same happens to me when I open the Railcraft coke oven GUI.

**Comment by loordgek** [comment]
mods need to update but ccc has an update

**Comment by Chicken-Bones** [comment]
Update EnderStorage
