### ISSUE TITLE
NEI item tooltips don't use Item.getFontRenderer(...)

### ISSUE THREAD

**Issue by asiekierka** [Chicken-Bones/NotEnoughItems#191]
This breaks BuildCraft 7 Recipe Package tooltips.

**Comment by asiekierka** [comment]
To reproduce, grab http://asie.pl/buildcraft-7.0.2.8.jar, place a Recipe Packager, package any recipe with it (for example, make a pattern of a pickaxe and then place the resources below) and check the tooltip. If it looks like "|S0 |S1 |S2", it's using vanilla font rendering. If it has pretty icons, it's using BuildCraft's.

**Comment by asiekierka** [comment]
What it is, I believe, is that GuiDraw's multiline tip function always forces the Minecraft font renderer. A variant with an item-specific font renderer should be provided there and then used in GuiContainerManager.renderTooltips.

**Comment by Chicken-Bones** [comment]
Fixed
CCL https://github.com/Chicken-Bones/CodeChickenLib/commit/42b022af2aac81935b9dd23cfb6c95f74700c995 (1.7.10-1.1.3.136)
CCC (1.7.10-1.0.6.39)
NEI fbcd6692ed0f7a2ac6b6e5a6a636d4abc363c5fe (1.7.10-1.0.4.98)

**Comment by asiekierka** [comment]
Thanks a lot!

**Comment by asiekierka** [comment]
Your solution has one last bug. Vanilla only uses a custom font renderer if getFontRenderer is non-null, so you should add a nullcheck there. Thanks!

**Comment by Chicken-Bones** [comment]
https://github.com/Chicken-Bones/NotEnoughItems/blob/d02fdc2f0bde3437c508ce9516e2a735fa24690d/src/codechicken/nei/guihook/GuiContainerManager.java#L100

**Comment by asiekierka** [comment]
Oh, okay

**Comment by Chicken-Bones** [comment]
No worries
