### ISSUE TITLE
server crash DW1.7.10 if i give new mods in

### ISSUE THREAD

**Issue by MCHanka** [Chicken-Bones/NotEnoughItems#194]
https://github.com/EpicCraft1/Crashes/tree/master here is mz problem :dancer:

**Comment by Chicken-Bones** [comment]
Buildcraft Addons with full inventory?

**Comment by MCHanka** [comment]
i have my server only 5 days i can you give my adress but first problem is with mods in :) i dont know why my server crash if i give more mods btw. warp book and others for versions 1.7.10 :) so can u help? here is adress 93.91.250.101:27894 you can join :) i use for login FTB launcher :dancer:

**Comment by MCHanka** [comment]
so i have full inventory yes i building new spawn area for players :)

but this making bug too but only in game

**Comment by Chicken-Bones** [comment]
Unfortunately I can't fix this, it's a BuildCraft addons issue, just don't try and spawn items when you have a full inventory.

**Comment by MCHanka** [comment]
ok thanks :) and i like your mods :) and you too :)

**Comment by Chicken-Bones** [comment]
Thanks, sorry I can't do more for you

**Comment by Chicken-Bones** [comment]
Try updating Buildcraft Compat

**Comment by MCHanka** [comment]
is updated :) and now going :) thanks
