### ISSUE TITLE
[Minor] Crash

### ISSUE THREAD

**Issue by Reyls** [Chicken-Bones/NotEnoughItems#195]
NotEnoughItems-1.7.10-1.0.4.95-universal
(So maybe already fixed)

https://gist.github.com/Reyls/4a5e6794e15ecc8343de
while minecraft was open I cleaned my keyboard ;)
So I don't now what keys where pressed.
Perhaps you are interested in

**Comment by Chicken-Bones** [comment]
Unfortunately this one isn't much use to me without knowing how to replicate it
