### ISSUE TITLE
Complete crash upon pressing "U"

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [Chicken-Bones/NotEnoughItems#197]
When I press U, my game crashes. Removing Botania does not fix this issue:

http://hastebin.com/rayuyoluje.1c

**Comment by Lebleus** [comment]
I got the same problem, it came when some mods are installed. I got it with these mods :
 - Magic Bees
 - Galacticraft
 - Magical Crops
 - ModularPowersuits

If you remove them, you don't have any crashes, but it's a big problem in NEI.

**Comment by Unrepentant-Atheist** [comment]
Was a Magic Bees issue. Solved.
