### ISSUE TITLE
Crash while looking up recipes.

### ISSUE THREAD

**Issue by ray10k** [Chicken-Bones/NotEnoughItems#206]
I am currently making a modpack and I've got it to the point where I can run a server with the pack. However, whenever I press U while hovering over an item to see what recipes its used in, minecraft crashes with the following crash log:
https://gist.github.com/ray10k/17292e5ab7f1025b2af0
 I'll try again without mods, to check if this is caused  by a mod conflict.
Side note, using NEI 1.0.4.105 and MC 1.7.10

**Comment by ray10k** [comment]
After some more experimentation, I've confirmed that the issue only occurs when using the following mods, along with the libraries they depend on:
NEI 1.0.4.105
magical crops 0.1
RotaryCraft v6f

I will notify the other authors as well.

**Comment by BionicFelps** [comment]
I can confirm this one, ran into it while updating my pack, although I haven't attempted to narrow it down yet (just went searching for anyone with a similar issue).  Considering I updated every mod in the pack, as well as my forge version I knew it could be literally anything... The previous version of this pack on Forge 1291 with RotaryCraftv6e and Magical Crops PUBLIC BETA 4.0 version 1 works fine, this may be something with RotaryCraft v6f...

**Comment by ReikaKalseki** [comment]
Either remove MagicCrops or wait for v7.

**Comment by Chicken-Bones** [comment]
Fixed c42edf53cf73f8b7603f067b180e5993918f8915 (1.7.10-1.0.4.107)
