### ISSUE TITLE
creative+ full inventory crash, not checking for room? 

### ISSUE THREAD

**Issue by plaguewolf** [Chicken-Bones/NotEnoughItems#207]
oops, well as the title says, in creative+(through NEI) when i cheat in a stack of items if there isnt room for the stack i get a client crash, not sure if this is related to inv tweaks, or NEI but im doing my rounds of bug reporting.

also ive notices some wierd behavior with mekanism liquid tanks from version x.x.x.228 and forge 1291-1351. whenever i search for tanks, it takes a good 30 seconds for all of mekanisms tanks to load, even when just switching from one page to another after the search. weirdness.

(seriosly forge, why you do that? 1355+ messing with yo fluids XD)

**Comment by Chicken-Bones** [comment]
logs? last check it was BuildCraft Compat that needed an update (but that was months ago)
Forge, fluids, eh, no idea why the load times are huge

**Comment by plaguewolf** [comment]
eh, it doesnt thrown any warn/errors in log, just odd that its only doing that with mekanism fluid tanks. i guess mekanism is doing something funky. cant update it either because the next version uses forge 1355+ and that breaks like half the mods in my pack. guess i'll live with it for now, until things get updated.
