### ISSUE TITLE
[Suggestion (API)]: Allow to disable the overlay for a certain GUI

### ISSUE THREAD

**Issue by Victorious3** [Chicken-Bones/NotEnoughItems#208]
I only have one slot in said GUI, it's not editable, and I don't even show the player inventory.
I found `NEIClientConfig.setInternalEnabled` which works as a workaround, but an API method might be more intuitive.

**Comment by Chicken-Bones** [comment]
```
API.registerNEIGuiHandler(INEIGuiHandler)
INEIGuiHandler.modifyVisiblity(VisiblityData)
VisiblityData.showNEI
```

Sorry it's kinda obscure, there's `INEIGuiAdapter` so you don't have to implement all the methods of the interface

**Comment by Victorious3** [comment]
Ah, thanks.
