### ISSUE TITLE
[1.7.10] Crash when opening the inventory

### ISSUE THREAD

**Issue by Ephys** [Chicken-Bones/NotEnoughItems#212]
NEI Version: 1.0.4.107:dev
CCC Version: 1.0.6.44:dev
Crash report: http://pastebin.com/cRXaT7hn

NEI is looking for GuiDraw.drawMultilineTip(font, x, y, tooltips) but it has been replaced by GuiDraw.drawMultilineTip(x, y, tooltips)
I couldn't find a newer NEI version, so I'm assuming this is a bug

**Comment by m31317015** [comment]
My friends got the same problem too, when they're in my lan world server.

**Comment by Chicken-Bones** [comment]
Try updating CodeChickenLib

**Comment by MrKickkiller** [comment]
Tried with an updated version of Nei, CodeChickenLib and CCC. Still resulting in the same error when opening inventory

https://gist.github.com/MrKickkiller/ecc9d4f62a2c553923ea
Version numbers @ line 1
Stack trace @ line 60

**Comment by GirafiStudios** [comment]
Do you have Waila installed too, when this crash happens?

**Comment by MrKickkiller** [comment]
@GirafiStudios I do. Version: 1.5.7a_1.7.10

**Comment by GirafiStudios** [comment]
Try this, unreleased version: http://mobiusstrip.eu/maven/mcp/mobius/waila/Waila/1.5.11-RC2-NONEI_1.7.10/Waila-1.5.11-RC2-NONEI_1.7.10.jar

**Comment by GirafiStudios** [comment]
I had the problem in my dev enviroment like a week ago, i think this was that fixed it, can't remember.

**Comment by MrKickkiller** [comment]
But the waila is part of a dependency (in my case). Just drop it in the mods folder I guess?

**Comment by GirafiStudios** [comment]
You're in a dev environment?

**Comment by MrKickkiller** [comment]
Yes indeed

**Comment by GirafiStudios** [comment]
Do:
repositories {
	maven {
        name "Mobius Repo"
        url "http://mobiusstrip.eu/maven"
    }
}
And compile "mcp.mobius.waila:Waila:1.5.11-RC2-NONEI_1.7.10" under dependencies, and run gradlew setupDecompWorkspace eclipse/idea

**Comment by MrKickkiller** [comment]
Yup, finally able to open up the inventory.
So cause is an outdated dependency on Waila then?

**Comment by GirafiStudios** [comment]
The problem is Waila indeed.

**Comment by Ephys** [comment]
Confirmed, updating both Waila-1.5.11-RC2-NONEI_1.7.10 and CCLib fixes the problem. Thank you !
