### ISSUE TITLE
[1.7.10 deobf] Error transforming method / Needle not found in Haystack

### ISSUE THREAD

**Issue by Choonster** [Chicken-Bones/NotEnoughItems#220]
Forge version: 1.7.10-10.13.4.1445-1.7.10 (dev/deobf)
NEI version: 1.0.5.110
CCC version: 1.0.7.46
CCL version: 1.1.3.138

Attempting to run the Minecraft Client from IDEA results in [this crash](https://gist.github.com/Choonster/8489196e43119f297b00).

The crash occurs in the [TestMod2](https://github.com/Choonster/TestMod2/tree/ee8470256e888dfaeeb0b3d6ccd76fdf2625e811) workspace, but not the [ChiselFacades](https://github.com/Choonster/ChiselFacades/tree/0bcdd8ff778411b7d4b09cfeb7939d681aa35885) workspace; despite both mods using the same Forge version, dependencies and mappings directory.

**Comment by Chicken-Bones** [comment]
double up on the mod?

**Comment by Choonster** [comment]
Ah, that was indeed the issue. Thanks.
