### ISSUE TITLE
[Request] Support for Forge's new brewing system

### ISSUE THREAD

**Issue by ganymedes01** [Chicken-Bones/NotEnoughItems#221]
It's been added recently and is included in the latest recommended version of Forge.
Here's the PR that got merged: https://github.com/MinecraftForge/MinecraftForge/commit/0373920f994562e850a3aad474b0e45585436f4d

It still maintains vanilla functionality so the current brewing recipe viewing you have should stay in place.

**Comment by The-Fireplace** [comment]
Just commenting to say I agree, you need to support this.

**Comment by Chicken-Bones** [comment]
Is there a mod that uses it with a known recipe list that I can test
against?

**Comment by The-Fireplace** [comment]
Yes, [UnLogic II](www.curse.com/mc-mods/minecraft/231078-unlogic-ii). Note that it requires [Fireplace Core](www.curse.com/mc-mods/minecraft/225536-fireplace-core).
If you would rather have dev/src builds, I can provide links.

Each of the 3 Souls(found in the UnLogic II creative tab) can be used as an ingredient, and the "input" potion is an Awkward Potion. The result is the one of the 3 Liquid UnLogic Gems, the color of the output matching the color of the soul.
