### ISSUE TITLE
NEI Stone bricks bug

### ISSUE THREAD

**Issue by Joshwoo69** [Chicken-Bones/NotEnoughItems#223]
http://pastebin.com/4y6z9WKw

**Comment by Chicken-Bones** [comment]
Need more info, how do I make this happen?

**Comment by Joshwoo69** [comment]
Swhen i try to craft a stone brick it shows a flat stone brick texture with a name and then the number -1

**Comment by Joshwoo69** [comment]
It might br the latest buildcraft...

**Comment by Joshwoo69** [comment]
Okay found the issue :
latest project red makes makes the stone bricks weird.

**Comment by Chicken-Bones** [comment]
Okay, report on Project Red github
