### ISSUE TITLE
[Mincecraft 1.8][NEI 1.0.5.104][CCC 1.0.5.36] Crash pressing 'F7' in SMP

### ISSUE THREAD

**Issue by lanord** [Chicken-Bones/NotEnoughItems#231]
When i press 'F7' the client crash. Here is the crash report : https://gist.github.com/lanord/0e62449cdb2103f4f458

Also i'm using sponge. Nothing happen in single player only in SMP. There is no error on the server, its only client side.

If you need anything else, just ask.

**Comment by GirafiStudios** [comment]
Doesn't happen to me. I'm not using Sponge either. Try using the recommended version of Minecraft Forge, and see if it happens ^^

**Comment by lanord** [comment]
Ok after further test. It only happen when I had the sponge mod.

Will report on the sponge issue tracker.

Thanks for the help.
