### ISSUE TITLE
[1.8] Tooltip crash, when hovering over lit redstone

### ISSUE THREAD

**Issue by GirafiStudios** [Chicken-Bones/NotEnoughItems#234]
This crash happens whenever you have enabled the "What-Am-I-Looking-At"-feature in NEI, and are hovering over lit redstone.

Crash log: http://pastebin.com/PDX5PP6g

**Comment by MoonCutter2B** [comment]
Hm, haven't tried that one, but it somehow reminds me of the flickering problem that I have reported.
I know that Waila and Elians Detector also have problem in 1.8 with flickering and presenting tool tips when hovering. I wonder if this is a more general problem...

**Comment by GirafiStudios** [comment]
There was a similiar problem in NEI for 1.8, but that was only when looking at lit redstone, and not having the tooltip enabled ^^

**Comment by jadenPete** [comment]
Download latest version. I had the same problem.
