### ISSUE TITLE
Crash When Viewing a Certain Page

### ISSUE THREAD

**Issue by jadenPete** [Chicken-Bones/NotEnoughItems#237]
Whenever I Viewed one Page on NEI the GUI (Not including the items menu) disappeared, and ten seconds later, it crashed. This has never happened before.  Here's my crash report:
http://pastebin.com/f8zJq9Ct

**Comment by GirafiStudios** [comment]
Try using the latest version of NEI, might solve your problem.

**Comment by jadenPete** [comment]
Solved.
