### ISSUE TITLE
[1.8] Lighting issue in inventory

### ISSUE THREAD

**Issue by GirafiStudios** [Chicken-Bones/NotEnoughItems#243]
Whenever you open your inventory, the world behind the inventory GUI for some reason shows very bright when NEI is intalled. Where it without NEI, have no changing in lighting at all. Tested on multiple computers.

With NEI installed (Tested with both version 1.0.5.82 and 1.0.5.104)
![skaermbillede 2015-07-21 23 55 57](https://cloud.githubusercontent.com/assets/6305377/8813634/4ec547ce-3005-11e5-9ef4-688ff7fb68d0.png)

Plain Forge, version 11.14.3.1450.
![skaermbillede 2015-07-22 00 01 41](https://cloud.githubusercontent.com/assets/6305377/8813637/55e1d126-3005-11e5-8f39-9a869aebbbb4.png)

**Comment by Chicken-Bones** [comment]
Tested with just NEI?

**Comment by GirafiStudios** [comment]
Yup the first screenshot is only NEI, CCC and CCL installed.
