### ISSUE TITLE
Latest 1.7.10 crash with Pixelmon

### ISSUE THREAD

**Issue by prodkid** [Chicken-Bones/NotEnoughItems#259]
http://pastebin.com/w13D2y9k

**Comment by alfw** [comment]
@prodkid can you reproduse this whiout kcauldron ?

**Comment by prodkid** [comment]
it occurs in singleplayer as well.

**Comment by Termin8or** [comment]
You've got loads of mods installed, why would you report this to forge, cause it's clearly one of the mods that is broken, I'm guessing Pixlemon, report it to them.

**Comment by clienthax** [comment]
@Termin8or not our end, was working fine before

**Comment by alfw** [comment]
@prodkid 
I argee with @Termin8or here. Try to reproduse this whit only chickebbones mods and Pixelmon. If same crash happen. It's most likly on he's end, if not it's one of the other mods.

Reason why i asked about kcauldron is i know that kcauldron many times make bad crashes. Ther are modders out ther that dosent take bug report / crases if they have only tested it on kcauldron. They normal respose is that test with pure forge server then if same crash happen ther, then come back. But i it only happens with kcauldron. Go to them for support.
