### ISSUE TITLE
[1.8 API Request] Add new variant of existing Item

### ISSUE THREAD

**Issue by Choonster** [Chicken-Bones/NotEnoughItems#270]
My [test mod](https://github.com/Choonster/TestMod3) creates an upgraded version of the vanilla Stone Sword ([implementation](https://github.com/Choonster/TestMod3/blob/master/src/main/java/com/choonster/testmod3/util/SwordUpgrades.java)) using the AttributeModifier system (so it's the same `Item` with some custom NBT) and adds this to its creative tab.

However, NEI ignores this variant of the Stone Sword and adding it with `API.addItemListEntry` replaces the default Stone Sword entry.

Would it be possible to implement a way to add a new variant of an existing `Item` without overwriting the default entries for it?

**Comment by Chicken-Bones** [comment]
The only difficulty I can see would be the default ordering in the items list. You specifically want to add variants of existing items, but they're not returned by the item's getSubItems method, and you don't want to override the entire list for that item

**Comment by Choonster** [comment]
One option for the ordering would be to add any new variants after the existing ones. So you'd end up with one of the following lists for each `Item` in order of priority (same priority as there is now):
* Override Variants (ignores New Variants)
* Sub Items + New Variants
* Damage search + New Variants

**Comment by Chicken-Bones** [comment]
43aaf0a32b90afcab2c6a63f078c066f521473a1 build TBA

**Comment by Choonster** [comment]
Nice, thanks.
