### ISSUE TITLE
My i use this and codechickencore in a modpack im making

### ISSUE THREAD

**Issue by huntdogy** [Chicken-Bones/NotEnoughItems#278]
Pm on curse with answer if you could

**Comment by GirafiStudios** [comment]
Taken from Chicken Bones post on MinecraftForum.net:
" ModPacks:
You are welcome to include any of my mods in modpacks as long as you provide credit. My name and a link to this page is fine "

**Comment by huntdogy** [comment]
okey dokey

**Comment by GirafiStudios** [comment]
Please close this again..
