### ISSUE TITLE
[Important] Usage at ore dict recipes determinates all other recipes!

### ISSUE THREAD

**Issue by xXGandalfXx** [Chicken-Bones/NotEnoughItems#283]
Hey,

after i had looked into the usage of for example a jungle plank, i can craft all recipes who uses the plankWood Ore Dict only with the jungle plank.

The same issue is available at all other ore dict based recipes.

Pls. fix this quickly :D 

P.S. i use NEI - 1.0.5.118 and CCC - 1.0.7.47

**Comment by DashFury** [comment]
that's not an NEI issue. NEI doesn't create or modify any recipe. It just shows them to you.

The Ore Dict is a forge feature, and its whole purpose is to let you do what you described as a bug. That is, crafting things made out of planks with any item registered as "plankWood". Why shouldn't you be able to craft those things with jungle planks only?

**Comment by xXGandalfXx** [comment]
Ok... I have figured out what is buggy and its IC2 :(

Sry for this bug report
