### ISSUE TITLE
1.7.10 Checking usage causes a large delay

### ISSUE THREAD

**Issue by Zsashas** [Chicken-Bones/NotEnoughItems#285]
Nothing appears in the console, no other problems, but every time I check item usage, it takes MUCH longer than it should, no matter what the item is or if it even has any uses at all. Recipe checking also delays, but not nearly as much.

**Comment by Dream-Master** [comment]
Not only the usage causes large delay if i have a big modpack (800 sites of items) and i type something in that i am searcheing it need a few seconds to show me the right items.

**Comment by Zsashas** [comment]
In my pack, searching doesn't have any delay. And the usage checking delay isn't just NEI, the whole game stops for several seconds. I'll post the modlist in a few hours when I get home, if needed.

**Comment by Zsashas** [comment]
Finally figured out what causes this. I had "Show item usage in Ore Dictonary" option enabled. It's from NEIPlugins it seems. Turning that off made it nearly instant to check usage.
