### ISSUE TITLE
[1.7.10] Anyone know how to run NEI in an IDE? It keeps crashing when I do it

### ISSUE THREAD

**Issue by ThePuzzlemaker** [Chicken-Bones/NotEnoughItems#288]
When I tried to run NEI in an IDE, it kept crashing, even when I did it multiple ways. Anyone know how to run it in an IDE?

**Comment by plaguewolf** [comment]
im assuming you want eclipse, and i dont even IDEA so meh.

grab the relevant dev versions, goto build path, add them as external jars under lib.

that worked for me.

if that doesnt work, try dropping them into he mods folder...? iunno.
