### ISSUE TITLE
omg! finally nailed that bug thats been persisting for months NEI / BC

### ISSUE THREAD

**Issue by plaguewolf** [Chicken-Bones/NotEnoughItems#295]
version info:
forge 1492
buildcraft 7.1.\* (for me the last 3 or 4 versions, including the latest 7.1.13)
buildcraft compat 7.1.2
codechickencore 1.0.7.47 (also was there for the last version or so)
NEI 1.0.5.118 (same as above, persisted through several versions)

bug description:
in NEI cheat mode, when inventory is full, and click on any item to "give to player" client hangs and crashes.

exception logs: http://pastebin.com/eYDES6Mj

i think something about NEI itemstack handling has changed and/or BC guicontainer isnt working with the changes right.

relevant issues:
https://github.com/BuildCraft/BuildCraft/issues/3125

**Comment by chloeprince** [comment]
SAME HERE!

https://gist.github.com/chloeprince/29e6344abcd159b833af

**Comment by plaguewolf** [comment]
yes. this is what that bug was caused by. however. dun dun dun!

i saw, somewhere else that another mod had actually fixed this bug being caused by thier own mod...
i think, it was sanguimancy...? dont quote me.
so maybe its on buildcrafts side? iunno.

**Comment by plaguewolf** [comment]
is this something that is know? is it BC or NEI? sorry to be obnoxious bump guy...
