### ISSUE TITLE
Can we have a 1.7.10 build?

### ISSUE THREAD

**Issue by ganymedes01** [Chicken-Bones/NotEnoughItems#305]
Sorry if this is not the place to ask for this, I didn't know how else to contact you. If I've done a booboo let me know and I'll slap myself in the hand =P

The last 1.7.10 build was from mid-october, so it would be nice to have a more recent one (even more so after the shift-clicking fix I PRed :D). I know it's easy to make my own build, and believe me I have. But I wouldn't feel comfortable distributing it (even if you said I could), and I know of many people interested in it.

**Comment by Dream-Master** [comment]
@ganymedes01 
I try to compile Nei but i failed. Not sure what i did wrong with the workspace. Can you make a Build and share it please.

**Comment by Fletcher1237** [comment]
The MIT license permits you to make a copy and do whatever you wish with it. If you could share your own build that would be greatly appreciated <3

**Comment by Chicken-Bones** [comment]
1.0.5.120

**Comment by Dream-Master** [comment]
:+1:

**Comment by ganymedes01** [comment]
Thank you <3

**Comment by Fletcher1237** [comment]
@Chicken-Bones <3
