### ISSUE TITLE
NEI Does not display blocks

### ISSUE THREAD

**Issue by mrdrewlego** [Chicken-Bones/NotEnoughItems#311]
The NEI now does not display blocks even if the the o key is pressed. The options and the other tabs though do appear with the different cheats. When in cheat mode though if i click on a block on cheat mode through the subsets neither the recipe key or the cheat key works. The only time I can now use a recipe is if I have it in my inventory or hand. If there is any additional information please tell me and I am currently using 1.7.10 with forge

**Comment by jmcaffee** [comment]
Why did you close? How was it fixed?
