### ISSUE TITLE
Shapeless Recipe Usage Crash (1.7.10)?

### ISSUE THREAD

**Issue by tankerkiller125** [Chicken-Bones/NotEnoughItems#332]
MC 1.7.10

http://pastebin.com/0h2NiJR6

It only happens when attempting to see an items uses. Is it because there are to many items or something?

**Comment by plaguewolf** [comment]
yeah. that. i would like to know as well.

relevant? hmmm, im playing with ~160 mods, so, id say there is a fair few items
