### ISSUE TITLE
can't add this mod to OreSpawn If I Add, It Crashes

### ISSUE THREAD

**Issue by ghost** [Chicken-Bones/NotEnoughItems#402]
I want to add this to orespawn but when i add it crashed, HELP!

**Comment by ghost** [comment]
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

**Comment by Korrosiv** [comment]
yeah it happens to me too. and orespawn without it is horrible
