### ISSUE TITLE
NEI is still getting stuck

### ISSUE THREAD

**Issue by ghost** [Chicken-Bones/NotEnoughItems#71]
NEI is getting stuck (you can still type in the search, but nothing happens in the item side) in a random time after gamestart. Latest NEI and CCC version are in use.

For me it's seems to only happen with AE2's sync search.
No guaranteed way to reproduce atm, still on it to get one going.

Releated issue: #26, #70, #124

**Comment by KWik** [comment]
Problem appears in ATLauncher Sky Factory 2.2.3 which uses CodeChickenCore-1.7.10-1.0.4.29, NotEnoughItems-1.7.10-1.0.3.77 and Waila-1.5.5_1.7.10 amongst other mods. Tested on a mac and a PC. Both stop working after a few hours of play. After restarting the client NEI works like a charm for about one lookup. After which I get alot of java.util.ConcurrentModificationException : null

Full log:
http://paste.atlauncher.com/view/fa38189c

**Comment by GirafiStudios** [comment]
@KWik you need to update Waila to the latest version for 1.7.10, that fixes it :)

**Comment by KWik** [comment]
On 30. jan. 2015, at 20:51, Girafi <notifications@github.com> wrote:

> @KWik you need to update Waila to the latest version for 1.7.10, that fixes it :)

The version i ATLauncher Sky Factory pack is still newer than the one stated as a fix in the thread.*

The comment is still valid insofar as others might come here looking for answers (I did, so it isn't that unlikely) and should see that it might be fixed but not completely in the version mentioned above. And quite a few use modpacks in the illusion that you can use them and escape having to keep the mods updated yourself. (See how I'm not disagreeing with your comment ;) )

*) 1.7.10-1.0.3.73 stated as a fix, 1.7.10-1.0.3.77 verified as having similar behavior.

-- 
KWik
Enduring bugs for a living.
